# Minimal pkgdown workflow
on:
  push:
    branches: [master]
  workflow_dispatch:

name: pkgdown

jobs:
  pkgdown:
    runs-on: ubuntu-latest
    container: rocker/verse:latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          install.packages(c("pkgdown", "R6", "yaml"))
        shell: Rscript {0}

      - name: Install package
        run: R CMD INSTALL .

      - name: Build static docs
        run: |
          pkgdown::build_site(new_process = FALSE)
        shell: Rscript {0}

      - name: Deploy to GitHub pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs
          branch: gh-pages
