# Minimal R CMD check workflow
on:
  push:
    branches: [master]
  workflow_dispatch:

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    container: rocker/verse:latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      
      - name: Install dependencies
        run: |
          install.packages(c("R6", "yaml"))
        shell: Rscript {0}

      - name: Install and check
        run: |
          R CMD INSTALL --no-docs --no-multiarch --no-test-load .
        shell: bash
